/** Path fragments appended to environment.apiBaseUrl by the axios instance. */
export const API_ENDPOINTS = Object.freeze({
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    logoutAll: '/auth/logout-all',
    refresh: '/auth/refresh',
    me: '/auth/me',
    sessions: '/auth/sessions',
    revokeSession: (sessionId) => `/auth/sessions/${sessionId}`,
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    acceptInvitation: '/auth/accept-invitation',
  },
  users: {
    base: '/users',
    byId: (id) => `/users/${id}`,
    activate: (id) => `/users/${id}/activate`,
    deactivate: (id) => `/users/${id}/deactivate`,
    lock: (id) => `/users/${id}/lock`,
    unlock: (id) => `/users/${id}/unlock`,
    statusHistory: (id) => `/users/${id}/status-history`,
    roles: (id) => `/users/${id}/roles`,
    changePassword: '/users/me/password',
  },
  roles: {
    base: '/roles',
    byId: (id) => `/roles/${id}`,
  },
  permissions: {
    base: '/permissions',
    byId: (id) => `/permissions/${id}`,
  },
  invitations: {
    base: '/invitations',
    byId: (id) => `/invitations/${id}`,
    resend: (id) => `/invitations/${id}/resend`,
  },
  batches: {
    base: '/batches',
    byId: (id) => `/batches/${id}`,
  },
  instructors: {
    base: '/instructors',
    byId: (id) => `/instructors/${id}`,
    referenceData: '/instructors/reference-data',
    photoUploadUrl: '/instructors/photo/upload-url',
  },
  students: {
    base: '/students',
    byId: (id) => `/students/${id}`,
    referenceData: '/students/reference-data',
    photoUploadUrl: '/students/photo/upload-url',
  },
  courses: {
    base: '/courses',
    byId: (id) => `/courses/${id}`,
    publish: (id) => `/courses/${id}/publish`,
    unpublish: (id) => `/courses/${id}/unpublish`,
    archive: (id) => `/courses/${id}/archive`,
    submit: (id) => `/courses/${id}/submit`,
    approve: (id) => `/courses/${id}/approve`,
    reject: (id) => `/courses/${id}/reject`,
    duplicate: (id) => `/courses/${id}/duplicate`,
    recordings: (id) => `/courses/${id}/recordings`,
    thumbnail: (id) => `/courses/${id}/thumbnail`,
    mine: '/courses/mine',
  },
  enrollments: {
    base: '/enrollments',
    byId: (id) => `/enrollments/${id}`,
  },
  adminEnrollments: {
    base: '/admin/enrollments',
    byId: (id) => `/admin/enrollments/${id}`,
    status: (id) => `/admin/enrollments/${id}/status`,
  },
  instructorEnrollments: {
    base: '/instructor/enrollments',
    byId: (id) => `/instructor/enrollments/${id}`,
    status: (id) => `/instructor/enrollments/${id}/status`,
  },
  learning: {
    course: (courseId) => `/courses/${courseId}`,
    lesson: (courseId, lessonId) => `/learning/courses/${courseId}/lessons/${lessonId}`,
    progress: (courseId) => `/learning/courses/${courseId}/progress`,
  },
  assessments: {
    base: '/student/assessments',
    byId: (id) => `/student/assessments/${id}`,
    attempts: (id) => `/student/assessments/${id}/start`,
    attemptsHistory: (id) => `/student/assessments/${id}/attempts`,
    submit: (attemptId) => `/student/assessments/attempts/${attemptId}/submit`,
    saveDraft: (attemptId) => `/student/assessments/attempts/${attemptId}/submissions`,
    result: (attemptId) => `/student/assessments/attempts/${attemptId}`,
    report: (attemptId) => `/student/assessments/attempts/${attemptId}/report`,
    recordingUploadUrl: (attemptId) => `/student/assessments/attempts/${attemptId}/recording/upload-url`,
    completeRecording: (attemptId) => `/student/assessments/attempts/${attemptId}/recording/complete`,
    uploadRecordingDirect: (attemptId) => `/student/assessments/attempts/${attemptId}/recording/upload`,
    recordingPlaybackUrl: (attemptId) => `/student/assessments/attempts/${attemptId}/recording/playback-url`,
  },
  adminAssessments: {
    base: '/admin/assessments',
    byId: (id) => `/admin/assessments/${id}`,
    publish: (id) => `/admin/assessments/${id}/publish`,
    unpublish: (id) => `/admin/assessments/${id}/unpublish`,
    close: (id) => `/admin/assessments/${id}/close`,
    archive: (id) => `/admin/assessments/${id}/archive`,
    duplicate: (id) => `/admin/assessments/${id}/duplicate`,
    questions: (assessmentId) => `/admin/assessments/${assessmentId}/questions`,
    questionById: (assessmentId, questionId) =>
      `/admin/assessments/${assessmentId}/questions/${questionId}`,
    updateQuestion: (questionId) => `/admin/assessments/questions/${questionId}`,
    analytics: (id) => `/admin/assessments/${id}/analytics`,
    resultAnalytics: (id) => `/admin/assessments/${id}/result-analytics`,
    extend: (id) => `/admin/assessments/${id}/extend`,
    schedule: (id) => `/admin/assessments/${id}/schedule`,
    retest: (assessmentId, studentId) => `/admin/assessments/${assessmentId}/students/${studentId}/retest`,
    rubrics: '/admin/assessments/rubrics',
    rubricById: (id) => `/admin/assessments/rubrics/${id}`,
    pendingGrading: '/admin/assessments/grading/pending',
    gradeAttempt: (attemptId) => `/admin/assessments/grading/attempts/${attemptId}/grade`,
  },
  certificates: {
    base: '/certificates',
    byId: (id) => `/certificates/${id}`,
    download: (id) => `/certificates/${id}/download`,
    verify: (serialNumber) => `/certificates/verify/${encodeURIComponent(serialNumber)}`,
  },
  notifications: {
    base: '/notifications',
    read: (id) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
  },
  analytics: {
    admin: '/analytics/admin',
    instructor: '/analytics/instructor',
    studentProgress: '/analytics/progress',
  },
  auditLogs: {
    base: '/admin/audit-logs',
  },
  subscriptions: {
    current: '/subscriptions/current',
    plans: '/subscriptions/plans',
    billingHistory: '/subscriptions/billing',
  },
  tenants: {
    current: '/organization',
    settings: '/organization',
    branding: '/organization',
  },
  profile: {
    base: '/profile',
    avatar: '/profile/avatar',
    changePassword: '/profile/change-password',
  },
  resources: {
    base: '/resources',
    byId: (id) => `/resources/${id}`,
    uploadUrl: '/resources/upload-url',
    uploadDirect: '/resources/upload',
    download: (id) => `/resources/${id}/download`,
    stream: (id) => `/resources/${id}/stream`,
  },
  gamification: {
    summary: '/gamification/me/summary',
    badges: '/gamification/me/badges',
    milestones: '/gamification/me/milestones',
    streak: '/gamification/me/streak',
    points: '/gamification/me/points',
    leaderboard: '/gamification/leaderboard',
    admin: {
      badges: '/admin/gamification/badges',
      badgeById: (id) => `/admin/gamification/badges/${id}`,
      levels: '/admin/gamification/levels',
      levelById: (id) => `/admin/gamification/levels/${id}`,
      milestones: '/admin/gamification/milestones',
      milestoneById: (id) => `/admin/gamification/milestones/${id}`,
      pointRules: '/admin/gamification/point-rules',
      pointRuleById: (id) => `/admin/gamification/point-rules/${id}`,
    },
  },
  calendar: {
    events: '/student/calendar',
    deadlines: '/student/calendar/deadlines',
  },
  studentNotes: {
    base: '/student/notes',
    byCourse: (courseId) => `/student/notes/course/${courseId}`,
    forLesson: (courseId, lessonId) => `/student/notes/course/${courseId}/lesson/${lessonId}`,
    delete: (noteId) => `/student/notes/${noteId}`,
  },
  studentBookmarks: {
    base: '/student/bookmarks',
    byCourse: (courseId) => `/student/bookmarks/course/${courseId}`,
    check: '/student/bookmarks/check',
    toggle: '/student/bookmarks/toggle',
    delete: (bookmarkId) => `/student/bookmarks/${bookmarkId}`,
  },
});
